// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_Blog_Property_In_BlogMetadata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Blog_Property_In_BlogMetadata));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130757449_Added_Blog_Property_In_BlogMetadata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
