// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Updating1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updating1));
        
        string IMigrationMetadata.Id
        {
            get { return "201309131301228_Updating1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
