// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Post_Rowversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Post_Rowversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201309140522171_Post_Rowversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
