// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Updating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updating));
        
        string IMigrationMetadata.Id
        {
            get { return "201309131300392_Updating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
