// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class none : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(none));
        
        string IMigrationMetadata.Id
        {
            get { return "201309150631570_none"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
