// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogCreatedBy_ColumnNameChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogCreatedBy_ColumnNameChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130734223_Blog.CreatedBy_ColumnNameChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
