// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Author1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Author1));
        
        string IMigrationMetadata.Id
        {
            get { return "201309141516498_Author1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
