// <auto-generated />
namespace ExamPrep.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Added_BlogMetadata_In_Blog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_BlogMetadata_In_Blog));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130751241_Added_BlogMetadata_In_Blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
