//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EMPLOYEEID { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string NATIVENAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> GENDER { get; set; }
        public Nullable<byte> MARITALSTATUS { get; set; }
        public string TEMPORARYADDRESS { get; set; }
        public string PERMANENTADDRESS { get; set; }
        public string CONTACTNO { get; set; }
        public string EMAILADDRESS { get; set; }
    }
}
